In [22]:
import pandas as pd
import numpy as np
df = pd.read_csv('/home/fleming/Desktop/blossom/env/Assignments/project 1/billboard.csv')
df

,artiste,track,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,x4th.week,x5th.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,Destiny's Child,Independent Women Part I,Rock,2000-09-23,2000-11-18,78,63.0,49.0,33.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Santana,"Maria, Maria",Rock,2000-02-12,2000-04-08,15,8.0,6.0,5.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Savage Garden,I Knew I Loved You,Rock,1999-10-23,2000-01-29,71,48.0,43.0,31.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Madonna,Music,Rock,2000-08-12,2000-09-16,41,23.0,18.0,14.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),Rock,2000-08-05,2000-10-14,57,47.0,45.0,29.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,Ghostface Killah,Cherchez LaGhost,R&B,2000-08-05,2000-08-05,98,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,"Smith, Will",Freakin' It,Rap,2000-02-12,2000-02-12,99,99.0,99.0,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,Zombie Nation,Kernkraft 400,Rock,2000-09-02,2000-09-02,99,99.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,"Eastsidaz, The",Got Beef,Rap,2000-07-01,2000-07-01,99,99.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,Fragma,Toca's Miracle,R&B,2000-10-28,2000-10-28,99,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df.replace(np.NaN,0)

,artiste,track,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,x4th.week,x5th.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,Destiny's Child,Independent Women Part I,Rock,2000-09-23,2000-11-18,78,63.0,49.0,33.0,23.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Santana,"Maria, Maria",Rock,2000-02-12,2000-04-08,15,8.0,6.0,5.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Savage Garden,I Knew I Loved You,Rock,1999-10-23,2000-01-29,71,48.0,43.0,31.0,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Madonna,Music,Rock,2000-08-12,2000-09-16,41,23.0,18.0,14.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),Rock,2000-08-05,2000-10-14,57,47.0,45.0,29.0,23.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,Ghostface Killah,Cherchez LaGhost,R&B,2000-08-05,2000-08-05,98,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313,"Smith, Will",Freakin' It,Rap,2000-02-12,2000-02-12,99,99.0,99.0,99.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
314,Zombie Nation,Kernkraft 400,Rock,2000-09-02,2000-09-02,99,99.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
315,"Eastsidaz, The",Got Beef,Rap,2000-07-01,2000-07-01,99,99.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
316,Fragma,Toca's Miracle,R&B,2000-10-28,2000-10-28,99,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
df['date.entered'] = pd.to_datetime(
                          df['date.entered'], 
                          #format='%Y%m%d'
) 
df['date.peaked'] = pd.to_datetime(
                          df['date.peaked'], 
                          #format='%Y%m%d'
)
df['x72nd.week'] = pd.to_numeric(
                          df['x72nd.week'],
) 
df.dtypes

artiste                 object
track                   object
genre                   object
date.entered    datetime64[ns]
date.peaked     datetime64[ns]
                     ...
x72nd.week             float64
x73rd.week             float64
x74th.week             float64
x75th.week             float64
x76th.week             float64
Length: 81, dtype: object

In [29]:
date_parser=lambda x: dt.datetime.strptime(x, '%d/%m/%Y')
df['entered_to_peak'] = df['date.peaked'] - df['date.entered']

#print(df)
df

,artiste,track,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,x4th.week,x5th.week,...,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week,entered_to_peak
0,Destiny's Child,Independent Women Part I,Rock,2000-09-23,2000-11-18,78,63.0,49.0,33.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56 days
1,Santana,"Maria, Maria",Rock,2000-02-12,2000-04-08,15,8.0,6.0,5.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56 days
2,Savage Garden,I Knew I Loved You,Rock,1999-10-23,2000-01-29,71,48.0,43.0,31.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98 days
3,Madonna,Music,Rock,2000-08-12,2000-09-16,41,23.0,18.0,14.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35 days
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),Rock,2000-08-05,2000-10-14,57,47.0,45.0,29.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,Ghostface Killah,Cherchez LaGhost,R&B,2000-08-05,2000-08-05,98,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0 days
313,"Smith, Will",Freakin' It,Rap,2000-02-12,2000-02-12,99,99.0,99.0,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0 days
314,Zombie Nation,Kernkraft 400,Rock,2000-09-02,2000-09-02,99,99.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0 days
315,"Eastsidaz, The",Got Beef,Rap,2000-07-01,2000-07-01,99,99.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0 days
316,Fragma,Toca's Miracle,R&B,2000-10-28,2000-10-28,99,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0 days

In [34]:
df['entered_to_peak'].dt.days

0      56
1      56
2      98
3      35
4      70
       ..
312     0
313     0
314     0
315     0
316     0
Name: entered_to_peak, Length: 317, dtype: int64

In [35]:
df[df['entered_to_peak']>32]

TypeError: Invalid comparison between dtype=timedelta64[ns] and int